# step 1 : Data Collection

## Download and get the data in the system 

we will use urlretrieve function to download the data from the github raw data

In [2]:
medical_data_url = 'https://raw.githubusercontent.com/JovianML/opendatasets/master/data/medical-charges.csv'

In [3]:
from urllib.request import urlretrieve

In [4]:
urlretrieve(medical_data_url,'medical.csv')

('medical.csv', <http.client.HTTPMessage at 0x18aa5229610>)

Now we can use this dataset to our  project as a pandas dataframe

In [5]:
# Importing pandas as pd

import pandas as pd

Making pandas data Frame

In [6]:
medical_df = pd.read_csv('medical.csv')

# Data Understanding


Learn how data is structured , what data is about and much more related to the data given

## objective : 

Our objective is to find a way to estimate the "the insurance charges" to apply based on the historical data we have . FOr that we need to establish the relationship between the data and the output ("Charges")

### Checking out the data little bit

In [7]:
medical_df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

We can see that this dataset have 7 columns . age , sex , bmi , smoker , region and charges .

In [8]:
medical_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

If we have to categorise the data based on the datatype we would get something like 

1. Numbers : age , bmi , children ( int), charges
2. string ( cateforical ) : sex , smoker , region 

- We can also see that there are no missing values in this dataset one task is remained

In [9]:
medical_df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

# Exploratory Analysis and visualization


- Now let's explore the data visually and try to understand the dataset by analysing it visually 
- we will also try to find the relationship between the data and the charges 

**Libraries we will use are**
1. matplotlib
2. seaborn
3. Plotly

In [10]:
!pip install plotly matplotlib seaborn --quiet

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\ADMIN\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [11]:
# Installing the neccesary libraries

import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

The following settings will improve tge default style and font sizes for our charts

In [12]:
sns.set_style('darkgrid')
matplotlib.rcParams['font.size']=14
matplotlib.rcParams['figure.figsize']=(10,6)
matplotlib.rcParams['figure.facecolor']='#000000'

## **Age**

Age is a numerica column . The minimum age in the dataset is 18 and the maximum age in the dataset is 64 . Thus we can visualise the distribution of age using a histogram with 47 bins ( one for each year ) and a box plot .We'll use the plotly to make the chart interactive , but you can create similar charts using seaborn